[build]
  cmd = "~/go/bin/templ generate && go build -o ./tmp/main ./cmd/server/main.go"
  entrypoint = "./tmp/main"
  include_ext = ["go", "templ", "json", "env"]
  exclude_dir = ["tmp", "vendor", "content", "static"]
  delay = 500
  kill_delay = 500

[log]
  time = false
