// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MouseTrail() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"trail\" aria-hidden=\"true\" style=\"position:fixed;top:0;left:0;pointer-events:none;z-index:8999;overflow:visible;\"></svg><script>\n\t(function () {\n\t\tvar svg = document.querySelector('svg.trail');\n\t\tvar path = document.createElementNS('http://www.w3.org/2000/svg', 'path');\n\t\tpath.setAttribute('fill', 'none');\n\t\tpath.setAttribute('stroke', '#8B5CF6');\n\t\tpath.setAttribute('stroke-width', '4');\n\t\tpath.setAttribute('stroke-linecap', 'round');\n\t\tpath.setAttribute('stroke-linejoin', 'round');\n\t\tpath.style.filter = 'drop-shadow(0 0 4px #8B5CF6)';\n\t\tsvg.appendChild(path);\n\t\tvar points = [];\n\t\tvar segments = 80;\n\t\tvar mouse = { x: 0, y: 0 };\n\n\t\tdocument.addEventListener('mousemove', function (e) {\n\t\t\tmouse.x = e.clientX;\n\t\t\tmouse.y = e.clientY;\n\n\t\t\tif (points.length === 0) {\n\t\t\t\tfor (var i = 0; i < segments; i++) {\n\t\t\t\t\tpoints.push({ x: mouse.x, y: mouse.y });\n\t\t\t\t}\n\t\t\t}\n\t\t});\n\n\t\tfunction resize() {\n\t\t\tvar ww = window.innerWidth;\n\t\t\tvar wh = window.innerHeight;\n\t\t\tsvg.style.width = ww + 'px';\n\t\t\tsvg.style.height = wh + 'px';\n\t\t\tsvg.setAttribute('viewBox', '0 0 ' + ww + ' ' + wh);\n\t\t}\n\n\t\tfunction anim() {\n\t\t\tif (points.length > 0) {\n\t\t\t\tvar px = mouse.x;\n\t\t\t\tvar py = mouse.y;\n\n\t\t\t\tpoints.forEach(function (p, index) {\n\t\t\t\t\tp.x = px;\n\t\t\t\t\tp.y = py;\n\n\t\t\t\t\tvar n = points[index + 1];\n\t\t\t\t\tif (n) {\n\t\t\t\t\t\tpx = px - (p.x - n.x) * 0.6;\n\t\t\t\t\t\tpy = py - (p.y - n.y) * 0.6;\n\t\t\t\t\t}\n\t\t\t\t});\n\n\t\t\t\tpath.setAttribute('d', 'M ' + points.map(function (p) { return p.x + ' ' + p.y; }).join(' L '));\n\t\t\t}\n\n\t\t\trequestAnimationFrame(anim);\n\t\t}\n\n\t\twindow.addEventListener('resize', resize);\n\t\tresize();\n\t\tanim();\n\t})();\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
